sonar.projectKey=deploy-devsecops-vite-project-jenkins
sonar.projectName=End-to-End DevSecOps CI/CD Pipeline with Automated Security Scanning
sonar.projectVersion=1.0
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.js,**/*.spec.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
